# Site settings
name: Steve Crowhurst
email: stevecrow@shaw.ca
#canonical_url:
keywords: "Game Audio, Software Engineer, Audio Programming, C++, Interactive Music, Wwise, Team Lead"
skills: "Senior/Principal Game Audio Programmer from Vancouver, BC, Canada"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/steve-crowhurst-369768115/

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 704FF2
  primary-rgb: "82, 64, 239"
  secondary: 553C70
  secondary-dark: 412F59
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
